<a href="https://colab.research.google.com/github/vp1099/Sentiment_Analysis_Heroku_Streamlit/blob/main/Sentiment_Analysis_Major_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
import pandas as pd
import numpy
df = pd.read_csv('Restaurant_Reviews.tsv',sep='\t')
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [71]:
#importing all the required libraries
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.stem import WordNetLemmatizer
from nltk import tokenize

In [72]:
#converting the reviews into lower case
#df.Review=df.Review.apply(lambda x: x.lower())
df


Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [73]:
!pip install contractions

In [74]:
import contractions

In [75]:
# Expanding contractions
def con(text):
  expand=contractions.fix(text)
  return expand

df.Review=df.Review.apply(con)
df['Review'][0]

'Wow... Loved this place.'

In [76]:
import re

def remove_sp(text):
  pattern=r'[^A-Za-z0-9\s]'
  text=re.sub(pattern,'',text)
  return text

df.Review=df.Review.apply(remove_sp)
df

Review  Liked
0                                 Wow Loved this place      1
1                                    Crust is not good      0
2             Not tasty and the texture was just nasty      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                            Appetite instantly gone      0
997  Overall I was not impressed and would not go back      0
998  The whole experience was underwhelming and I t...      0
999  Then as if I had not wasted enough of my life ...      0

[1000 rows x 2 columns]

In [77]:
import string
punctuations=list(string.punctuation)

In [78]:
df.Review=df.Review.apply(lambda x : " ".join(x for x in x.split() if x not in punctuations))

In [79]:
# Removing stopwords
nltk.download('stopwords')
stopword_list=stopwords.words('english')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [80]:
stopword_list.remove('no')
stopword_list.remove('not')


In [81]:
df.Review=df.Review.apply(lambda x : " ".join(x for x in x.split() if x not in stopword_list))
df['Review'][5]

'Now I getting angry I want damn pho'

In [ ]:
nltk.download('punkt')

In [83]:
df['Review']=df.Review.apply(word_tokenize)
df['Review'][0]


['Wow', 'Loved', 'place']

In [84]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [85]:
lemmatizer=WordNetLemmatizer()


In [86]:
df['Review']=df.Review.apply(lambda x:[lemmatizer.lemmatize(word) for word in x])

In [87]:
df


Review  Liked
0                                  [Wow, Loved, place]      1
1                                   [Crust, not, good]      0
2                         [Not, tasty, texture, nasty]      0
3    [Stopped, late, May, bank, holiday, Rick, Stev...      1
4                 [The, selection, menu, great, price]      1
..                                                 ...    ...
995         [I, think, food, flavor, texture, lacking]      0
996                        [Appetite, instantly, gone]      0
997  [Overall, I, not, impressed, would, not, go, b...      0
998  [The, whole, experience, underwhelming, I, thi...      0
999  [Then, I, not, wasted, enough, life, poured, s...      0

[1000 rows x 2 columns]

In [88]:


df.Review= df.Review.astype(str)



In [89]:
import numpy as np
review_list=df['Review'].array
review_list.shape


(1000,)

In [105]:
x = df.iloc[:,0].values
y = df.iloc[:,1].values


array(["['Wow', 'Loved', 'place']", "['Crust', 'not', 'good']",
       "['Not', 'tasty', 'texture', 'nasty']",
       "['Stopped', 'late', 'May', 'bank', 'holiday', 'Rick', 'Steve', 'recommendation', 'loved']",
       "['The', 'selection', 'menu', 'great', 'price']",
       "['Now', 'I', 'getting', 'angry', 'I', 'want', 'damn', 'pho']",
       "['Honeslty', 'not', 'taste', 'THAT', 'fresh']",
       "['The', 'potato', 'like', 'rubber', 'could', 'tell', 'made', 'ahead', 'time', 'kept', 'warmer']",
       "['The', 'fry', 'great']", "['A', 'great', 'touch']",
       "['Service', 'prompt']", "['Would', 'not', 'go', 'back']",
       "['The', 'cashier', 'no', 'care', 'ever', 'I', 'say', 'still', 'ended', 'wayyy', 'overpriced']",
       "['I', 'tried', 'Cape', 'Cod', 'ravoli', 'chicken', 'cranberrymmmm']",
       "['I', 'disgusted', 'I', 'pretty', 'sure', 'human', 'hair']",
       "['I', 'shocked', 'no', 'sign', 'indicate', 'cash']",
       "['Highly', 'recommended']",
       "['Waitress', 'li

In [107]:


#!pip install -U scikit-learn

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0)


In [108]:
import sklearn
sklearn_version = sklearn.__version__
print(sklearn_version)

1.0.2


In [109]:
print(x_train.shape)
x_test.shape


(750,)


(250,)

In [110]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC


In [111]:
final = Pipeline([('Vect',TfidfVectorizer()),
                  ('model',SVC(probability=True))])

In [112]:
final.fit(x_train,y_train)

Pipeline(steps=[('Vect', TfidfVectorizer()), ('model', SVC(probability=True))])

In [113]:
y_pred=final.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0])

In [114]:
y_test

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0])

In [115]:
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix
sklearn_version = sklearn.__version__
print(sklearn_version)

1.0.2


In [116]:
accuracy_score(y_pred,y_test)

0.812

In [117]:
confusion_matrix(y_pred,y_test)

array([[102,  32],
       [ 15, 101]])

In [118]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.87      0.76      0.81       134
           1       0.76      0.87      0.81       116

    accuracy                           0.81       250
   macro avg       0.82      0.82      0.81       250
weighted avg       0.82      0.81      0.81       250



In [119]:
x_test[1]

"['Worst', 'foodservice', 'I']"

In [120]:
final.predict([x_test[1]])

array([0])

In [123]:
x_test[7]

"['If', 'food', 'not', 'bad', 'enough', 'enjoy', 'dealing', 'world', 'worstannoying', 'drunk', 'people']"

In [124]:
final.predict([x_test[7]])

array([0])

In [125]:
[x_test[17]]

["['Perhaps', 'I', 'caught', 'night', 'judging', 'review', 'I', 'not', 'inspired', 'go', 'back']"]

In [126]:
final.predict([x_test[17]])

array([0])

In [141]:
import pickle
pickle.dump(final,open('sentiment_analysis_models.p','wb'))